# Generated by Django 5.2.11 on 2026-03-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_planexercise_options_workoutlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutlog',
            old_name='users',
            new_name='user',
        ),
    ]
