# Generated by Django 6.0.5 on 2026-05-19 14:34

from django.db import migrations, models

VALID_CATEGORIES = {
    'chest', 'back', 'legs', 'shoulders', 'arms', 'core', 'cardio',
}
VALID_EXERCISE_TYPES = {
    'compound', 'isolation', 'bodyweight', 'cardio',
}


def normalize_exercise_choices(apps, schema_editor):
    Exercise = apps.get_model('workout', 'Exercise')
    for exercise in Exercise.objects.all():
        category = (exercise.category or '').strip().lower()
        if category not in VALID_CATEGORIES:
            category = 'chest'

        exercise_type = (exercise.exercise_type or '').strip().lower()
        if exercise_type not in VALID_EXERCISE_TYPES:
            exercise_type = 'compound'

        if exercise.category != category or exercise.exercise_type != exercise_type:
            exercise.category = category
            exercise.exercise_type = exercise_type
            exercise.save(update_fields=['category', 'exercise_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_workoutplan_owner_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='type',
            new_name='exercise_type',
        ),
        migrations.RunPython(
            normalize_exercise_choices,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(
                choices=[
                    ('chest', 'Chest'),
                    ('back', 'Back'),
                    ('legs', 'Legs'),
                    ('shoulders', 'Shoulders'),
                    ('arms', 'Arms'),
                    ('core', 'Core'),
                    ('cardio', 'Cardio'),
                ],
                default='chest',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(
                choices=[
                    ('compound', 'Compound'),
                    ('isolation', 'Isolation'),
                    ('bodyweight', 'Bodyweight'),
                    ('cardio', 'Cardio'),
                ],
                default='compound',
                max_length=30,
            ),
        ),
    ]
