# Generated by Django 6.0.5 on 2026-05-19 14:42

import django.db.models.deletion
from django.db import migrations, models


def deduplicate_plan_exercises(apps, schema_editor):
    PlanExercise = apps.get_model('workout', 'PlanExercise')
    seen = set()
    for row in PlanExercise.objects.order_by('plan_id', 'exercise_id', 'order', 'id'):
        key = (row.plan_id, row.exercise_id)
        if key in seen:
            row.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_exercise_choices_and_rename_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='planexercise',
            name='rest_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planexercise',
            name='target_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planexercise',
            name='target_sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_exercises', to='workout.exercise'),
        ),
        migrations.AlterField(
            model_name='planexercise',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_exercises', to='workout.workoutplan'),
        ),
        migrations.RunPython(
            deduplicate_plan_exercises,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='planexercise',
            constraint=models.UniqueConstraint(fields=('plan', 'exercise'), name='unique_plan_exercise'),
        ),
    ]
