# Generated by Django 6.0.5 on 2026-05-19 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_plan_exercise_targets_and_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_logs', to='workout.workoutplan'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workoutlog',
            index=models.Index(fields=['user', '-date'], name='workout_wor_user_id_f0e2d1_idx'),
        ),
    ]
