# Generated by Django 6.0.5 on 2026-05-19 15:12

import django.utils.timezone
import workout.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_workoutlog_related_names_and_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='data',
            field=models.JSONField(validators=[workout.validators.validate_workout_log_data]),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
